name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check version
        run: |
          VERSION=refs/tags/v
          VERSION+=$(cat package.json | jq -r .version)
          if [ $VERSION != '${{ github.ref }}' ]; then
            echo "Git tag doesn't match the version in package.json"
            exit 1
          fi

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Pack
        run: npm pack

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: vue-json-viewer-*.tgz
          fail_on_unmatched_files: true
